springrest:
  spring.h2.console:
    enabled=true
    path=/h2
  spring.datasource:
    url=jdbc:h2:mem:testdb
    driverClassName=org.h2.Driver
    username=sa
    password=
  spring.jpa:
    hibernate.ddl-auto = update
    database-platform=org.hibernate.dialect.H2Dialect
  spring.mvc.contentnegotiation:
    favor-parameter=true
    favor-path-extension=true
  spring.mvc.pathmatch:
    use-suffix-pattern=true
